// Entirely fictional identities and sample contacts; never send mail/SMS to seed data.
export const firstNames = [
  'Aarav',
  'Meera',
  'Rohan',
  'Ananya',
  'Vikram',
  'Priya',
  'Karan',
  'Neha',
  'Arjun',
  'Isha',
  'Ravi',
  'Suresh',
  'Manoj',
  'Deepak',
  'Salim',
  'Joseph',
  'Kavya',
  'Dev',
  'Aditi',
  'Nikhil',
  'Pooja',
  'Rahul',
  'Sneha',
  'Varun',
  'Divya',
  'Akash',
  'Shreya',
  'Aditya',
  'Nandini',
  'Sanjana',
  'Harish',
  'Lakshmi',
  'Pranav',
  'Ritu',
  'Vivek',
  'Swathi',
  'Mohan',
  'Rekha',
  'Siddharth',
  'Gauri',
  'Tarun',
  'Anjali',
  'Naveen',
  'Suman',
  'Ajay',
];
export const surnames = [
  'Sharma',
  'Iyer',
  'Mehta',
  'Rao',
  'Singh',
  'Nair',
  'Patel',
  'Verma',
  'Das',
  'Kapoor',
  'Kumar',
  'Yadav',
  'Gupta',
  'Joshi',
  'Khan',
  'Thomas',
];

export const categoryCatalog = [
  ['Plumbing', 'Pipes, taps and drainage', 25],
  ['Electrical', 'Wiring, lighting and circuits', 22],
  ['Air Conditioning', 'Cooling and AC servicing', 15],
  ['Carpentry', 'Doors, cabinets and fixtures', 9],
  ['Cleaning', 'Deep cleaning and sanitation', 8],
  ['Lift', 'Elevator repairs and safety', 5],
  ['Water Supply', 'Pressure, tanks and supply', 8],
  ['Common Area', 'Shared spaces and safety', 6],
  ['Security', 'Legacy intercom and access issues', 1],
  ['Other', 'Legacy miscellaneous repairs', 1],
] as const;

// Each technician has 2–3 skills, with at least two eligible technicians per category.
export const skillGroups = [
  [0, 6],
  [1, 2],
  [3, 7],
  [4, 7],
  [5, 1],
  [0, 6, 4],
  [1, 2, 5],
  [3, 7, 8],
  [4, 7, 9],
  [0, 6, 8],
  [1, 2, 9],
  [0, 3],
  [5, 8],
];

// name, unit price (INR), minimum stock
export const partCatalog = [
  ['Water Valve', 450, 8],
  ['PVC Pipe', 180, 10],
  ['Tap Washer', 25, 15],
  ['Drain Trap', 280, 6],
  ['Electrical Switch', 120, 10],
  ['Socket', 220, 8],
  ['MCB', 650, 5],
  ['LED Bulb', 160, 12],
  ['Fuse', 40, 12],
  ['Wire Roll', 900, 5],
  ['AC Capacitor', 850, 5],
  ['Copper Pipe', 700, 6],
  ['AC Filter', 550, 5],
  ['Door Lock', 1100, 4],
  ['Door Hinge', 160, 8],
  ['Screw Pack', 60, 15],
  ['Sealant', 240, 10],
  ['Cleaning Solution', 320, 8],
  ['Brush Head', 180, 6],
  ['Lift Sensor', 2800, 3],
  ['Pressure Gauge', 750, 4],
  ['Float Valve', 600, 5],
  ['Intercom Relay', 900, 3],
  ['Legacy Ballast', 350, 3],
  ['Legacy Door Handle', 300, 4],
] as const;

export const partsByCategory = [
  [0, 1, 2, 3, 16],
  [4, 5, 6, 7, 8, 9],
  [10, 11, 12],
  [13, 14, 15, 16],
  [17, 18],
  [19, 6],
  [0, 20, 21],
  [7, 14, 15],
  [22],
  [15, 16],
];

export const requestTemplates = [
  [
    'Bathroom tap leaking',
    'Kitchen sink drainage blocked',
    'Flush inlet valve not shutting',
    'Washbasin trap leaking',
  ],
  [
    'Power socket sparking',
    'Corridor light not working',
    'Circuit breaker trips repeatedly',
    'Bedroom switch is loose',
  ],
  [
    'Bedroom AC not cooling',
    'AC indoor unit dripping water',
    'AC outdoor unit unusually noisy',
    'AC airflow reduced',
  ],
  [
    'Main door lock damaged',
    'Wardrobe hinge coming loose',
    'Kitchen cabinet door misaligned',
    'Balcony door difficult to close',
  ],
  [
    'Balcony drain needs deep cleaning',
    'Stairwell needs sanitation',
    'Waste room needs cleaning',
    'Lobby tiles stained',
  ],
  [
    'Lift making unusual noise',
    'Lift door sensor unreliable',
    'Lift stops unevenly at floor',
    'Lift cabin light faulty',
  ],
  [
    'Water pressure is very low',
    'Overhead tank float valve stuck',
    'Water pump pressure fluctuates',
    'Supply pipe vibration',
  ],
  [
    'Staircase handrail loose',
    'Lobby door hinge damaged',
    'Parking light not working',
    'Corridor safety fixture loose',
  ],
  [
    'Intercom call not connecting',
    'Entrance access relay unreliable',
    'Security cabin switch faulty',
  ],
  [
    'Utility shelf bracket loose',
    'Service room seal needs repair',
    'Notice board fixture damaged',
  ],
] as const;
export const urgentTitles: Record<number, string> = {
  0: 'Severe bathroom pipe burst',
  1: 'Electrical short circuit near socket',
  2: 'AC wiring emitting burning smell',
  3: 'Main entrance door cannot be secured',
  4: 'Hazardous spill blocking staircase',
  5: 'Lift breakdown with door stuck',
  6: 'Major water supply pipe rupture',
  7: 'Staircase safety handrail detached',
  8: 'Entrance access lock failed',
  9: 'Loose fixture creating safety hazard',
};
export const diagnoses = [
  'Inlet valve seal has failed.',
  'Socket contacts show heat damage.',
  'AC capacitor has degraded.',
  'Door fitting is worn and misaligned.',
  'Drain and floor have accumulated debris.',
  'Lift sensor needs calibration.',
  'Supply pressure regulator is worn.',
  'Shared-space fitting is loose.',
  'Access relay contacts are worn.',
  'Fixture mounting has loosened.',
];
export const repairs = [
  'Replaced worn seal and tested water flow.',
  'Replaced damaged fitting and verified electrical safety.',
  'Serviced cooling components and tested operation.',
  'Adjusted fittings and checked smooth closure.',
  'Cleaned affected area and checked drainage.',
  'Replaced sensor and verified safe lift operation.',
  'Repaired pressure fitting and tested supply.',
  'Secured fitting and checked shared-space safety.',
  'Repaired access relay and verified operation.',
  'Replaced mounting hardware and inspected stability.',
];
export const residentMessages = [
  'Please call before arriving; someone will be at home.',
  'The issue has become more noticeable since yesterday.',
  'I can provide access after lunch.',
  'Photos and details have been shared with the office.',
  'Thank you for arranging the inspection.',
];
export const adminMessages = [
  'A matching technician has been scheduled.',
  'Please confirm access with the resident.',
  'Replacement materials have been approved.',
  'Please update the request after inspection.',
];
export const technicianMessages = [
  'I have inspected the issue and identified the cause.',
  'A replacement component is needed for a reliable repair.',
  'Repair is underway; final checks will follow.',
  'The repair has passed functional checks.',
];
export const feedbackMessages = [
  'Issue resolved quickly and properly.',
  'Technician was helpful and explained the repair.',
  'Repair was good but took longer than expected.',
  'Issue was fixed but I had to follow up twice.',
  'Service needs better coordination and communication.',
];
